"use client";
import { useEffect, useState } from "react";

export default function StockAnalyzer() {
  const [stocks, setStocks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchStocks = async () => {
      const stockNames = [
        "Punjab National Bank",
        "Indian Overseas Bank",
        "NTPC Green Energy",
        "Canara Bank",
        "IDBI Bank",
        "NHPC",
        "Suzlon Energy",
        "GMR Airports",
        "NMDC",
        "Vodafone Idea",
        "Yes Bank",
        "UCO Bank",
        "Bank of India",
        "IDFC First Bank",
        "Central Bank of India",
        "Bank of Maharashtra",
        "SJVN",
        "Punjab & Sind Bank",
        "IRB Infrastructure Developers",
        "OLA Electric Mobility",
        "NBCC (India)",
        "Motherson Sumi Wiring India",
        "Reliance Power",
        "Niva Bupa Health Insurance Company",
        "Trident",
        "Tata Teleservices (Maharashtra)",
        "HFCL",
        "IFCI",
        "TV18 Broadcast",
        "NMDC Steel Ltd.",
        "Jammu & Kashmir Bank",
        "Zee Entertainment Enterprises",
        "Jaiprakash Power Ventures",
        "SBFC Finance",
        "Tata Steel BSL",
        "JM Financial",
        "Edelweiss Financial Services",
        "MMTC",
        "Alok Industries",
        "Paradeep Phosphates",
        "Lloyds Engineering Works",
        "Network18 Media & Investments",
        "Equitas Small Finance Bank",
        "Shree Renuka Sugars",
        "PC Jeweller",
        "South Indian Bank",
        "Electrosteel Castings",
        "Spicejet",
        "RattanIndia Enterprises",
        "Ujjivan Small Finance Bank",
        "Shree Global Tradefin Ltd.",
        "Infibeam Avenues",
        "RattanIndia Power",
        "Jaiprakash Associates",
        "Hindustan Construction Company",
        "Sterlite Technologies",
        "EaseMyTrip",
        "National Fertilizers",
        "Jain Irrigation Systems",
        "Grauer & Weil (India)",
        "Magellanic Cloud",
        "Patel Engineering",
        "Dhani Services",
        "Imagicaaworld Entertainment",
        "Paisalo Digital",
        "Fedbank Financial Services Ltd",
        "JTL Industries Ltd",
        "Restaurant Brands Asia",
        "Allcargo Logistics",
        "Gateway Distriparks",
        "Jayaswal Neco Industries",
        "Brightcom Group",
        "Jamna Auto Industries",
        "Mahanagar Telephone Nigam",
        "Utkarsh Small Finance Bank",
        "Morepen Laboratories",
        "Bajaj Hindusthan Sugar",
        "Alembic",
        "Hathway Cable & Datacom",
        "Delta Corp",
        "Sindhu Trade Links",
        "Shipping Corporation of India Land and Assets Ltd.",
        "DCW",
        "Polo Queen Industrial & Fintech",
        "SEPC",
        "PTC India Financial Services",
        "Geojit Financial Services",
        "Urja Global",
        "GTL Infrastructure",
        "Dhani Services - Partly Paid",
        "Jyoti Structures",
        "Mishtann Foods",
        "Welspun Specialty Solutions",
        "Confidence Petroleum India",
        "Motisons Jewellers",
        "Max India Ltd",
        "Filatex India",
        "Cupid",
        "JSW Ispat Special Products",
        "Paramount Communications",
        "Gallantt Ispat",
        "Meghmani Organics",
        "Cropster Agro",
        "Wardwizard Inno Mobi Partly Paid",
        "Salasar Techno Engineering",
        "Sanstar",
        "GVK Power & Infrastructure",
        "HMA Agro Industries",
        "Rama Steel Tubes",
        "Southern Petrochemical Industries Corporation",
        "DEN Networks",
        "Syncom Formulations (India)",
        "ESAF Small Finance Bank",
        "Andhra Paper",
        "Jagran Prakashan",
        "Vakrangee Limited",
        "Andrew Yule & Co",
        "PNB Gilts",
        "Orient Green Power Company",
        "Udaipur Cement Works",
        "MIC Electronics",
        "Omaxe",
        "Balmer Lawrie Investments",
        "Dolat Algotech",
        "Mukand",
        "Shanti Educational Initiatives",
        "Spright Agro",
        "Coffee Day Enterprises",
        "Sanghi Industries",
        "Sigachi Industries",
        "Blue Cloud Softech Solutions",
        "Capital India Finance",
        "Mufin Green Finance",
        "Media Matrix Worldwide",
        "Shriram Properties",
        "Dhanlaxmi Bank",
        "Mercury Ev-Tech",
        "Dish TV India",
        "Madras Fertilizers",
        "MSP Steel & Power",
        "NACL Industries",
        "Yatra Online Ltd",
        "B L Kashyap & Sons",
        "Elpro International",
        "BMW Industries",
        "Fedders Holding",
        "KMC Speciality Hospitals (India)",
        "Hardwyn India",
        "Radhika Jeweltech",
        "Centrum Capital",
        "Pacheli Industrial Finance",
        "BCL Industries",
        "Vintage Coffee and Beverages",
        "Xchanging Solutions",
        "Sat Industries",
        "Shree Digvijay Cement Co",
        "Tuticorin Alkali Chemicals & Fertilizers",
        "Andhra Sugars",
        "Manali Petrochemicals",
        "Mukka Proteins",
        "TGV SRAAC",
        "Inertia Steel Limited",
        "Steel Exchange India",
        "Indo Rama Synthetics (India)",
        "Allcargo Gati",
        "Sportking India",
        "Shiva Cement",
        "Prabhat Dairy",
        "Oswal Greentech",
        "Jaybharat Textiles & Real Estate",
        "Bigbloc Construction",
        "AVT Natural Products",
        "Saurashtra Cement",
        "Western Carriers (India)",
        "HLV",
        "Rico Auto Industries",
        "Sadhana Nitro Chem",
        "Zee Media Corporation",
        "VL E-Governance & IT Solutions",
        "Kamdhenu",
        "Peninsula Land",
        "Hazoor Multi Projects",
        "Oswal Agro Mills",
        "Vascon Engineers",
        "Subex",
        "Snowman Logistics",
        "Suratwwala Business Group",
        "Sakuma Exports",
        "Balaji Telefilms",
        "TruCap Finance",
        "Rushil Decor",
        "Dwarikesh Sugar Industries",
        "Satia Industries",
        "Jay Bharat Maruti",
        "Allcargo Terminals",
        "Transindia Real Estate",
        "Premier Polyfilm",
        "R & B Denims",
        "GHCL Textiles Ltd.",
        "Hampton Sky Realty",
        "Arihant Capital Markets",
        "Wardwizard Innovations & Mobility",
        "Bodal Chemicals",
        "Reliance Communications",
        "Swiss Military Consumer Goods",
        "Foods and Inns",
        "Munjal Auto Industries",
        "Twamev Construction And Infrastructure",
        "Primo Chemicals",
        "GFL",
        "Sutlej Textiles & Industries",
        "Asian Granito India",
        "Worth Investment & Trading Co",
        "PVP Ventures",
        "Radiant Cash Management Services",
        "Equippp Social Impact Technologies",
        "Sarveshwar Foods",
        "BIO GREEN PAPERS LTD",
        "TPL Plastech",
        "Tamilnadu Petroproducts",
        "Spencer's Retail",
        "Colab Platforms",
        "Tracxn Technologies",
        "Nectar Lifesciences",
        "Oricon Enterprises",
        "Integrated Industries",
        "SBC Exports",
        "Hindustan Media Ventures",
        "Lancer Container Lines",
        "Andhra Cements",
        "Visaka Industries",
        "Vikas Lifecare",
        "Parsvnath Developers",
        "Essar Shipping",
        "Ugar Sugar Works",
        "Stallion India Fluorochemicals",
        "Menon Bearings",
        "Onmobile Global",
        "Tiger Logistics India",
        "Advani Hotels & Resorts (India)",
        "Kisan Mouldings",
        "Sadbhav Engineering",
        "Megasoft",
        "Khaitan Chemicals & Fertilizers",
        "Rudra Ecovation",
        "Vishal Fabrics",
        "Emami Paper Mills",
        "Shree Rama Newsprint",
        "Arfin India",
        "Digispice Technologies",
        "Scooters India",
        "Medico Remedies",
        "Dewan Housing Finance Corporation",
        "Artemis Electricals and Projects",
        "Rajnish Wellness",
        "Captain Polyplast",
        "Nandan Denim",
        "WS Industries India",
        "FCS Software Solutions",
        "PTL Enterprises",
        "Mangalam Global Enterprise",
        "Orient Paper & Industries",
        "Hindustan Motors",
        "Evexia Lifecare",
        "MBL Infrastructure",
        "Kriti Nutrients",
        "Xtglobal Infotech",
        "Sarla Performance Fibers",
        "Andhra Petrochemicals",
        "Gokul Refoils & Solvent",
        "Davangere Sugar Company",
        "Nova Agritech",
        "Genus Paper & Boards",
        "HP Adhesives",
        "Sintex Industries",
        "Rajasthan Gases",
        "Prozone Realty",
        "Bartronics India",
        "Alankit",
        "Manaksia",
        "Shree Tirupati Balajee Agro Trading Company Ltd",
        "Zim Laboratories",
        "HT Media",
        "Nikhil Adhesives",
        "Bharat Seats",
        "Orient Ceratech",
        "Sinclairs Hotels",
        "CL Educate",
        "Dhampur Bio Organics",
        "Sunshine Capital",
        "Mirza International",
        "HCL Infosystems",
        "International Conveyors",
        "Alacrity Securities",
        "Vikas Ecotech",
        "3i Infotech",
        "Niyogin Fintech",
        "Ashima",
        "BPL",
        "Shivam Autotech",
        "AB Infrabuild",
        "KCP Sugar & Industries Corporation",
        "Nagarjuna Fertilizers & Chemicals",
        "Alstone Textiles (India)",
        "Valiant Laboratories",
        "Nila Infrastructures",
        "Singer India",
        "Vipul",
        "BGR Energy Systems",
        "Kanoria Chemicals & Industries",
        "Almondz Global Securities",
        "Rubfila International",
        "UY Fincorp",
        "OK Play India",
        "Shardul Securities",
        "Ajanta Soya",
        "OCCL Ltd.",
        "Aerpace Industries",
        "Jaypee Infratech",
        "Exxaro Tiles",
        "Axita Cotton",
        "Reliance Capital",
        "Ansal Properties & Infrastructure",
        "Ravinder Heights",
        "Raj Television Network",
        "MIRC Electronics",
        "Airan",
        "Supreme Holdings & Hospitality (India)",
        "Zenotech Laboratories",
        "Quint Digital",
        "Future Retail",
        "Shish Industries",
        "Pasupati Acrylon",
        "Music Broadcast",
        "Rudra Global Infra Products",
        "Pritika Auto Industries",
        "ASI Industries",
        "Comfort Intech",
        "Inspirisys Solutions",
        "Mawana Sugars",
        "Graviss Hospitality",
        "Manaksia Steels",
        "Take Solutions",
        "Rama Phosphates",
        "Rohit Ferro-Tech",
        "VIP Clothing",
        "Bharat Road Network",
        "Vaarad Ventures",
        "Harshil Agrotech",
        "Akme Fintrade (India)",
        "NDL Ventures",
        "Pil Italica Lifestyle",
        "Bhatia Communications & Retail (India)",
        "Vintron Informatics",
        "IL&FS Investment Managers",
        "Gennex Laboratories",
        "Tierra Agrotech",
        "Shradha AI Technologies",
        "Sakthi Finance",
        "McLeod Russel India",
        "Ambalal Sarabhai Enterprises",
        "Madhav Infra Projects",
        "GTT Data Solutions",
        "Menon Pistons",
        "UFO Moviez India",
        "Jaysynth Orgochem",
        "Aayush Wellness",
        "Akme Star Housing Finance",
        "Gujarat Sidhee Cement",
        "Yogi",
        "Maral Overseas",
        "Autoline Industries",
        "Uma Exports",
        "Oxygenta Pharmaceutical",
        "MK Exim (India)",
        "BAG Films & Media",
        "Jay Shree Tea & Industries",
        "Integra Essentia",
        "Gujarat Toolroom",
        "True Green Bio Energy",
        "DRC Systems India",
        "Swadeshi Polytex",
        "Commercial Syn Bags",
        "Indian Wood Products Co",
        "Newtime Infrastructure",
        "Atlantaa",
        "KM Sugar Mills",
        "Nila Spaces",
        "Bharat Agri Fert & Realty",
        "Bhilwara Technical Textiles",
        "Anik Industries",
        "Niraj Cement Structurals",
        "Byke Hospitality",
        "MK Proteins",
        "Sakthi Sugars",
        "Bannari Amman Spinning Mills",
        "Trigyn Technologies",
        "Surana Telecom & Power",
        "Plaza Wires",
        "Khoday India",
        "Gourmet Gateway India",
        "Virinchi Limited",
        "Birla Precision Technologies",
        "Bhagyanagar India",
        "Leading Leasing Finance & Investment Company",
        "LGB Forge",
        "Gujarat Natural Resources",
        "Capital Trade Links",
        "Pharmaids Pharmacuticals",
        "Ashapuri Gold Ornament",
        "Kanoria Energy & Infrastructure",
        "Zodiac Clothing Company",
        "Noida Toll Bridge Company",
        "Manaksia Coated Metals & Industries",
        "Sicagen India",
        "Rathi Steel & Power",
        "Arunjyoti Bio Ventures Ltd.",
        "Gayatri Projects",
        "AION-Tech Solutions",
        "Sangam Finserv",
        "Mangalam Industrial Finance",
        "Waterbase",
        "J C T",
        "Country Club Hospitality & Holidays",
        "Aarnav Fashions",
        "Galaxy Cloud Kitchens",
        "Mercantile Ventures",
        "RPP Infra Projects",
        "Kesar Petroproducts",
        "Cressanda Railway Solutions",
        "Captain Pipes",
        "Udayshivakumar Infra",
        "Aksh Optifibre",
        "SREI Infrastructure Finance",
        "Vishwaraj Sugar Industries",
        "Zee Learn",
        "Scan Steels",
        "Variman Global Enterprises",
        "Aban Offshore",
        "Reliance Home Finance",
        "Praxis Home Retail",
        "Confidence Futuristic Energetech",
        "Kimia Biosciences",
        "Global Offshore Services",
        "Abans Enterprises",
        "Indowind Energy",
        "Tilak Ventures Partly Paid",
        "Indiabulls Enterprises",
        "North Eastern Carrying Corporation",
        "Innovassynth Investments",
        "RRIL",
        "Empower India",
        "Hilton Metal Forging",
        "Shree Rama Multi-Tech",
        "GP Petroleums",
        "KBC Global",
        "Rana Sugars",
        "Purple Finance",
        "Murudeshwar Ceramics",
        "A2Z Infra Engineering",
        "Stratmont Industries",
        "Bombay Rayon Fashions",
        "Alliance Integrated Metaliks",
        "Shah Metacorp",
        "SORIL Infra Resources",
        "Bodhi Tree Multimedia",
        "Ruchi Infrastructure",
        "Milkfood",
        "Nitco",
        "Seacoast Shipping Services",
        "CHL",
        "Regency Fincorp",
        "Milgrey Finance & Investments",
        "Omax Autos",
        "Magnum Ventures",
        "Rainbow Foundations",
        "AMJ Land Holdings",
        "Sharat Industries",
        "Upsurge Investment & Finance",
        "Silverline Technologies",
        "Coromandel Engineering Company",
        "Ducon Infratechnologies",
        "Eros International Media",
        "Ginni Filaments",
        "Lancor Holdings",
        "MPS Infotecnics",
        "SBEC Sugar",
        "Sprayking",
        "Gamco",
        "Hindustan Organic Chemicals",
        "Sah Polymers",
        "GEE",
        "MEP Infrastructure Developers",
        "HB Estate Developers",
        "Sera Investments & Finance India",
        "Oil Country Tubular",
        "Jyoti",
        "Odyssey Corporation",
        "Visa Steel",
        "Umang Dairies",
        "Winsome Textile Industries",
        "Archidply Industries",
        "PMC Fincorp",
        "Navkar Urbanstructure",
        "7Seas Entertainment",
        "Future Consumer",
        "ATV Projects India",
        "Sadbhav Infrastructure Projects",
        "Shyam Century Ferrous",
        "GG Engineering",
        "Ultracab (India)",
        "Syschem (India)",
        "India Steel Works",
        "Modern India",
        "Prajay Engineers Syndicate",
        "Regis Industries",
        "LA Tim Metal & Industries",
        "Mukta Arts",
        "Maximus International",
        "LKP Securities",
        "Arshiya",
        "Inventure Growth & Securities",
        "Surana Solar",
        "Indian Terrain Fashions",
        "Sanmit Infra",
        "Texmo Pipes & Products",
        "BLS Infotech",
        "Zeal Aqua",
        "South India Paper Mills",
        "SAL Steel",
        "Century Extrusions",
        "Indian Infotech & Software",
        "Generic Engineering Construction & Projects",
        "Globus Power Generation",
        "Compucom Software",
        "Vedavaag Systems",
        "Mangalam Drugs & Organics",
        "Mauria Udyog",
        "Sharp India",
        "Indian Sucrose",
        "Surat Trade and Mercantile",
        "Active Clothing Co",
        "Candour Techtex",
        "Raj Oil Mills",
        "Signet Industries",
        "Gujarat State Financial Corp",
        "Tarmat",
        "Bal Pharma",
        "Adhunik Industries",
        "Nath Industries",
        "VJTF Eduservices",
        "Shah Alloys",
        "Pioneer Embroideries",
        "Manaksia Aluminium Company",
        "Krebs Biochemicals & Industries",
        "Rajshree Sugars & Chemicals",
        "Astal Laboratories",
        "Seya Industries",
        "Coral India Finance & Housing",
        "Hindusthan National Glass & Industries",
        "Piccadily Sugar & Allied Industries",
        "Royal India Corporation",
        "GTL",
        "Indbank Merchant Banking Services",
        "Nettlinx",
        "Shahlon Silk Industries",
        "Sanwaria Consumer",
        "Vinny Overseas",
        "Tree House Education & Accessories",
        "Softrak Venture Investment",
        "BITS",
        "Rungta Irrigation",
        "Credent Global Finance",
        "Lovable Lingerie",
        "Umiya Buildcon",
        "Cambridge Technology Enterprises",
        "Bilcare",
        "Edvenswa Enterprises",
        "Precision Electronics",
        "Atal Realtech",
        "Maruti Infrastructure",
        "Baid Leasing & Finance Co",
        "Modern Threads (India)",
        "Future Supply Chain Solutions",
        "Alka India",
        "Bhagyanagar Properties",
        "Avance Technologies",
        "KIC Metaliks",
        "Tilak Ventures",
        "Sintex Plastics Technology",
        "GSS Infotech",
        "Bhandari Hosiery Exports",
        "Mideast Integrated Steels",
        "Setco Automotive",
        "Pro Fin Capital Services",
        "Standard Industries",
        "Rajnish Retail",
        "Lotus Eye Hospital & Institute",
        "Calcom Vision",
        "Surya Lakshmi Cotton Mills",
        "Kati Patang Lifestyle",
        "Basant Agro Tech (India)",
        "DB (International) Stock Brokers",
        "Digidrive Distributors",
        "Markolines Traffic Controls",
        "Prakash Steelage",
        "Brahmaputra Infrastructure",
        "Deep Polymers",
        "Mitsu Chem Plast",
        "Goyal Aluminiums",
        "Vaswani Industries",
        "BN Rathi Securities",
        "Fiberweb (India)",
        "Standard Capital Markets",
        "JHS Svendgaard Laboratories",
        "Landmarc Leisure Corporation",
        "Kohinoor Foods",
        "Ai Champdany Industries",
        "SGL Resources",
        "Gammon Infrastructure Projects",
        "Samor Reality",
        "Opto Circuits (India)",
        "BCPL Railway Infrastructure",
        "Narbada Gems & Jewellery",
        "Digicontent",
        "Parvati Sweetners & Power",
        "Baroda Extrusion",
        "Kkalpana Industries (India)",
        "Tahmar Enterprises",
        "Remedium Lifecare",
        "Bihar Sponge Iron",
        "Modern Dairies",
        "Sambhaav Media",
        "Pulsar International",
        "Ausom Enterprise",
        "Bharat Gears",
        "Indsil Hydro Power & Manganese",
        "Atam Valves",
        "Vibrant Global Capital",
        "Advik Capital",
        "Tomorrow Technologies Global Innovations",
        "SPL Industries",
        "Genpharmasec",
        "Radhe Developers (India)",
        "GV Films",
        "Vandana Knitwear",
        "Orissa Bengal Carrier",
        "Kushal",
        "Wardwizard Foods and Beverages",
        "Landmark Property Development Company",
        "Patel Integrated Logistics",
        "Sampann Utpadan India",
        "Aarey Drugs & Pharmaceuticals",
        "Parnax Lab",
        "GACM Technologies",
        "Lahoti Overseas",
        "Texel Industries",
        "Simbhaoli Sugars",
        "Rexnord Electronics & Controls",
        "Birla Tyres",
        "Flexituff Ventures International",
        "Accel",
        "Fortis Malar Hospitals",
        "Bansal Roofing Products",
        "Constronics Infra",
        "Super Tannery",
        "Ballarpur Industries",
        "Expo Gas Containers",
        "Flomic Global Logistics",
        "Electrotherm (India)",
        "Virat Leasing",
        "Akshar Spintex",
        "Lasa Supergenerics",
        "Suvidhaa Infoserve",
        "Prabhat Telecoms (India)",
        "Kretto Syscon",
        "Energy Development Company",
        "Virat Crane Industries",
        "Indian Acrylics",
        "AAA Technologies",
        "Future Enterprises",
        "Ind Swift",
        "SecMark Consultancy",
        "Mohite Industries",
        "Royal Cushion Vinyl Products",
        "Fervent Synergies",
        "Sundaram Multi Pap",
        "Motor & General Finance",
        "Vidli Restaurants",
        "Vishal Bearings",
        "Winsome Breweries",
        "Trescon",
        "WeP Solutions",
        "HB Portfolio",
        "Bharat Immunologicals & Biologicals Corporation",
        "Eco Hotels & Resorts",
        "Yamini Investments Company",
        "Compuage Infocom",
        "Morarjee Textiles",
        "Soma Textiles & Industries",
        "Sel Manufacturing Company",
        "Dhatre Udyog",
        "Athena Global Technologies",
        "Indrayani Biotech",
        "Cybermate Infotek",
        "Power & Instrumentation (Gujarat)",
        "Anmol India",
        "Faze Three Autofab",
        "Yuvraaj Hygiene Products",
        "Suraj Industries",
        "Zenith Steel Pipes & Industries",
        "Chowgule Steamships",
        "Cubex Tubings",
        "Bang Overseas",
        "Kothari Fermentation & Biochem",
        "Nilachal Refractories",
        "ARC Finance",
        "Caspian Corporate Services",
        "Suditi Industries",
        "Srestha Finvest",
        "Future Lifestyle Fashions",
        "WSFX Global Pay",
        "Nagreeka Exports",
        "Aimco Pesticides",
        "Morgan Ventures",
        "Toyam Sports",
        "Chandrima Mercantiles",
        "Prerna Infrabuild",
        "Tayo Rolls",
        "Som Datt Finance Corporation",
        "Atlas Jewellery India",
        "Chartered Logistics",
        "Shri Krishna Devcon",
        "Tera Software",
        "Alkali Metals",
        "AMD Industries",
        "Adtech Systems",
        "Resonance Specialties",
        "Barak Valley Cements",
        "Shristi Infrastructure Development Corporation",
        "Shreeji Translogistics",
        "Parle Industries",
        "Luharuka Media & Infra",
        "Superior Industrial Enterprises",
        "Canopy Finance",
        "Anjani Foods",
        "BLB",
        "Regency Ceramics",
        "Krishanveer Forge",
        "Titan Securities",
        "NRB Industrial Bearings",
        "Phoenix International",
        "Cinevista",
        "Saptarishi Agro Industries",
        "Arnold Holdings",
        "Shalimar Wires Industries",
        "Facor Alloys",
        "Reliable Data Services",
        "Kranti Industries",
        "Kaizen Agro Infrabuild",
        "Orient Press",
        "Kemistar Corporation",
        "Tulsyan NEC",
        "Bheema Cements",
        "Remi Edelstahl Tubulars",
        "IEL",
        "Saboo Sodium Chloro",
        "Globalspace Technologies",
        "Ansal Housing",
        "Dhanashree Electronics",
        "Supra Pacific Financial Services",
        "Apoorva Leasing Finance & Investment Company",
        "SVP Global Textiles",
        "Uniply Industries",
        "Rama Vision",
        "Relicab Cable Manufacturing",
        "Kesar Terminals & Infrastructure",
        "Gujarat Credit Corporation",
        "Amrapali Industries",
        "Ashnoor Textile Mills",
        "Ishan Dyes and Chemicals",
        "Kovilpatti Lakshmi Roller Flour Mills",
        "AMPVOLTS",
        "Transcorp International",
        "Archit Organosys",
        "Kesar Enterprises",
        "Future Enterprises - DVR",
        "Himalaya Food International",
        "VMS Industries",
        "Biofil Chemicals & Pharmaceuticals",
        "Kanishk Steel Industries",
        "Damodar Industries",
        "Pioneer Investcorp",
        "Sellwin Traders",
        "Paras Petrofils",
        "Cerebra Integrated Technologies",
        "Oriental Trimex",
        "Royale Manor Hotels & Industries",
        "Securekloud Technologies",
        "BSEL Algo",
        "JA Finance",
        "APM Industries",
        "Vivid Mercantile",
        "Banas Finance",
        "Minal Industries",
        "Supra Trends",
        "Vivimed Labs",
        "Yaari Digital Integrated Services",
        "Inter Globe Finance",
        "Bannari Amman Spinning Mills Limited - RE",
        "Mefcom Capital Markets",
        "Welcure Drugs & Pharmaceuticals",
        "Delta Manufacturing",
        "Secur Credentials",
        "Ovobel Foods",
        "KBS India",
        "East West Freight Carriers",
        "Dhampure Speciality Sugars",
        "Jeevan Scientific Technology",
        "JMT Auto",
        "Aspira Pathlab & Diagnostics",
        "Flex Foods",
        "NCL Research and Financial Services",
        "Porwal Auto Components",
        "Vikas WSP",
        "Prudential Sugar Corporation",
        "Riddhi Corporate Services",
        "Veeram Securities",
        "Grovy India",
        "Gayatri Sugars",
        "TPI India",
        "Nidhi Granites",
        "VSF Projects",
        "Lykis",
        "Sunil Healthcare",
        "Super Crop Safe",
        "Alfa Transformers",
        "Celebrity Fashions",
        "Skyline Millars",
        "Rolta India",
        "Shiva Mills",
        "Chrome Silicon",
        "Divyashakti",
        "Aplab",
        "Kore Foods",
        "Siti Networks",
        "F Mec International Financial Services",
        "Kapil Raj Finance",
        "Sam Industries",
        "Polylink Polymers (India)",
        "Rasi Electrodes",
        "Orient Tradelink",
        "Riba Textiles",
        "Swarnsarita Jewels India",
        "Biogen Pharmachem Industries",
        "HOV Services",
        "JBF Industries",
        "Archies",
        "Gujarat Poly Electronics",
        "Modulex Construction Technologies",
        "PCS Technology",
        "Valencia Nutrition",
        "Vivo Bio Tech",
        "Thakral Services (India)",
        "Narendra Investments (Delhi)",
        "Sri Havisha Hospitality & Infrastructure",
        "Godavari Drugs",
        "Jet Freight Logistics",
        "Shreyas Intermediates",
        "Sampre Nutritions",
        "New Light Apparels",
        "Vista Pharmaceuticals",
        "Diligent Media Corporation",
        "3P Land Holdings",
        "SVC Industries",
        "Balkrishna Paper Mills",
        "Tamilnadu Telecommunication",
        "Franklin Industries",
        "Comfort Fincap",
        "Sumedha Fiscal Services",
        "RDB Real Estate Constructions",
        "Shree Krishna Paper Mills & Industries",
        "Kay Power & Paper",
        "Trimurthi",
        "Ceeta Industries",
        "Aarvee Denims & Exports",
        "Banaras Beads",
        "Krypton Industries",
        "Rathi Bars",
        "Spectrum Foods",
        "Anjani Synthetics",
        "E-Land Apparel",
        "Ankit Metal & Power",
        "SKIL Infrastructure",
        "Malu Paper Mills",
        "Keerthi Industries",
        "Mena Mani Industries",
        "Ladderup Finance",
        "Real Eco Energy",
        "ICDS",
        "Sumeet Industries",
        "Supreme Infrastructure India",
        "Astron Paper & Board Mill",
        "Prime Property Development Corp",
        "Hiliks Technologies",
        "Pradhin",
        "Jindal Hotels",
        "Anand Rayons",
        "Cimmco",
        "Consolidated Construction Consortium",
        "Cranex",
        "Starlog Enterprises",
        "Smiths & Founders India",
        "Aro Granite Industries",
        "Futuristic Solutions",
        "NHC Foods",
        "Ecoboard Industries",
        "Karma Energy",
        "Pan India Corp",
        "HB Stockholdings",
        "MediCaps",
        "ARSS Infrastructure Projects",
        "Ravi Kumar Distilleries",
        "IFL Enterprises",
        "Containerway International",
        "Burnpur Cement",
        "Punjab Communications",
        "Modipon",
        "Gujarat Terce Laboratories",
        "Conart Engineers",
        "ISL Consulting",
        "Innovative Tech Pack",
        "Excel Realty N Infra",
        "Cranes Software International",
        "Joindre Capital Services",
        "TCFC Finance",
        "Metal Coatings (India)",
        "Mercator",
        "Balasore Alloys",
        "Super Spinning Mills",
        "Madhucon Projects",
        "Johnson Pharmacare",
        "Sri KPR Industries",
        "Pressure Sensitive Systems India",
        "Warren Tea",
        "Restile Ceramics",
        "Dynamic Portfolio Management & Services",
        "Raaj Medisafe India",
        "Salem Erode Investments",
        "Manjeera Constructions",
        "Sacheta Metals",
        "Kwality",
        "Omnipotent Industries",
        "Omkar Speciality Chemicals",
        "Lee & Nee Softwares (Exports)",
        "Jagan Lamps",
        "We Win",
        "Transchem",
        "Raminfo",
        "AD-Manum Finance",
        "Uttam Galva Steels",
        "Ushdev International",
        "Jetking Infotrain",
        "Gorani Industries",
        "Yash Chemex",
        "Kamadgiri Fashion",
        "Roopa Industries",
        "USG Tech Solutions",
        "Trans India House Impex Ltd",
        "Nam Securities",
        "Modern Converters",
        "Krishna Ventures",
        "Aastamangalam Finance",
        "Colorchips New Media",
        "Swasti Vinayaka Synthetics",
        "Saven Technologies",
        "Contil India",
        "Insilco",
        "MT Educare",
        "Future Market Networks",
        "MY Money Securities",
        "Gini Silk Mills",
        "Nova Iron & Steel",
        "G.S. Auto International",
        "GTN Industries",
        "Dhanlaxmi Fabrics",
        "Transwarranty Finance",
        "Vikas Proppant & Granite",
        "Sharanam Infraproject & Trading",
        "Continental Securities",
        "Pritish Nandy Communications",
        "Sahara One Media & Entertainment",
        "Oceanic Foods",
        "Manugraph India",
        "Growington Ventures India",
        "Tirupati Sarjan",
        "Sandu Pharmaceuticals",
        "Trident Texofab",
        "National Plastic Industries",
        "BAMPSL Securities",
        "Enbee Trade & Finance",
        "Kalyan Capitals",
        "Savani Financials",
        "Quasar India",
        "SRU Steels",
        "Tecil Chemicals and Hydro Power",
        "Ascensive Educare",
        "Impex Ferro Tech",
        "Diana Tea Co",
        "PBM Polytex",
        "IndiaNivesh",
        "Shangar Decor",
        "Artefact Projects",
        "India Home Loan",
        "Nakoda Group of Industries",
        "E L Forge",
        "CCL International",
        "Kreon Finnancial Services",
        "Pearl Polymers",
        "Shalimar Productions",
        "Meera Industries",
        "Kiduja India",
        "Rapicut Carbides",
        "Baba Arts",
        "Country Condo's",
        "Satchmo Holdings",
        "Tejnaksh Healthcare",
        "JHS Svendgaard Retail Ventures",
        "SMIFS Capital Markets",
        "Hind Aluminium Industries",
        "Kenvi Jewels",
        "Deccan Health Care",
        "Kanani Industries",
        "Gayatri Bioorganics",
        "Tatia Global Vennture",
        "MM Rubber Company",
        "Ambica Agarbathies Aroma & Industries",
        "Hemadri Cements",
        "Jumbo Bag",
        "Thinkink Picturez",
        "Bridge Securities",
        "Ashoka Metcast",
        "Diligent Industries",
        "Medico Intercontinental",
        "KJMC Financial Services",
        "Addi Industries",
        "NK Industries",
        "Earum Pharmaceuticals",
        "SJ Corporation",
        "Salora International",
        "Gokak Textiles",
        "ANG Lifesciences India",
        "KG Denim",
        "ACME Resources",
        "Adroit Infotech",
        "Kridhan Infra",
        "Advance Metering Technology",
        "Next Mediaworks",
        "Arigato Universe",
        "Ajcon Global Services",
        "Maharashtra Corporation",
        "Mohit Paper Mills",
        "Ashirwad Steels & Industries",
        "Duro Pack",
        "Ind Bank Housing",
        "Galactico Corporate Services",
        "Picturehouse Media",
        "Alfavision Overseas (India)",
        "Archana Software",
        "Rollatainers",
        "Sujala Trading & Holdings",
        "Bhaskar Agro Chemicals",
        "Citadel Realty & Developers",
        "Titan Intech",
        "Chandra Prabhu International",
        "Arman Holdings",
        "Sainik Finance & Industries",
        "Khaitan (India)",
        "Accedere",
        "Lakhotia Polyesters (India)",
        "GKB Ophthalmics",
        "Aditya Spinners",
        "Kabsons Industries",
        "Gautam Gems",
        "Zodiac Ventures",
        "Gowra Leasing & Finance",
        "Mega Corporation",
        "Axel Polymers",
        "VAMA Industries",
        "ETT",
        "Shreevatsaa Finance & Leasing",
        "Consecutive Investments & Trading Co",
        "Julien Agro Infratech",
        "KK Shah Hospitals",
        "Narmada Agrobase",
        "Ashirwad Capital",
        "Kanco Tea & Industries",
        "Archidply Decor",
        "Shree Ganesh BioTech India",
        "KSS",
        "Winpro Industries",
        "Pratik Panels",
        "Bervin Investment & Leasing",
        "Ravileela Granites",
        "Gujarat Inject Kerala",
        "Unison Metals",
        "Bonlon Industries",
        "Camex",
        "Bombay Talkies",
        "Sugal & Damani Share Brokers",
        "Epuja Spiritech",
        "Uniply Decor",
        "Dharani Sugars & Chemicals",
        "Binani Industries",
        "Madhav Marbles & Granites",
        "LCC Infotech",
        "Nagarjuna Agri Tech",
        "Polyspin Exports",
        "Unick Fix-A-Form & Printers",
        "Shiva Global Agro Industries",
        "Visagar Financial Services",
        "Haryana Leather Chemicals",
        "Genus Prime Infra",
        "Siel Financial Services",
        "Nalin Lease Finance",
        "Jaihind Synthetics",
        "QGO Finance",
        "Fortune International",
        "Onesource Industries And Ventures",
        "EPIC Energy",
        "Frontier Capital",
        "Ashnisha Industries",
        "Vivanta Industries",
        "Palm Jewels",
        "Balurghat Technologies",
        "TGB Banquets & Hotels",
        "Vineet Laboratories",
        "Garment Mantra Lifestyle",
        "Infomedia Press",
        "MPDL",
        "Umiya Tubes",
        "Gujarat Petrosynthese",
        "Sulabh Engineers & Services",
        "Rishi Techtex",
        "Pasupati Spinning & Weaving Mills",
        "STL Global",
        "Smart Finsec",
        "RR Metalmakers India",
        "Informed Technologies India",
        "Medinova Diagnostic Services",
        "Mishka Exim",
        "Standard Surfactants",
        "Premier Energy & Infrastructure",
        "Vasudhagama Enterprises",
        "Martin Burn",
        "Margo Finance",
        "Lesha Industries",
        "Nivaka Fashions",
        "Hybrid Financial Services",
        "White Organic Retail",
        "Sharika Enterprises",
        "Kisaan Parivar Industries",
        "Khandwala Securities",
        "Swasti Vinayaka Art & Heritage Corporation",
        "Inani Marbles & Industries",
        "Aruna Hotels",
        "UR Sugar Industries",
        "Centenial Surgical Suture",
        "Integrated Financial Services",
        "K-Lifestyle & Industries",
        "21st Century Management",
        "Tijaria Polypipes",
        "Shree Rajasthan Syntex",
        "VERTEX Securities",
        "Nirmitee Robotics India",
        "Comfort Commotrade",
        "Sawaca Enterprises",
        "Garnet Construction",
        "PVV Infra",
        "DSJ Communications",
        "Panjon",
        "Poona Dal & Oil Industries",
        "KJMC Corporate Advisors (India)",
        "Standard Batteries",
        "Invigorated Business Consulting",
        "Add-Shop E-Retail",
        "Chordia Food Products",
        "Bodhtree Consulting",
        "Garden Silk Mills Ltd",
        "Mercury Trade Links",
        "Pranavaditya Spinning Mills",
        "JMJ Fintech",
        "Anupam Finserv",
        "Prismx Global Ventures",
        "Salguti Industries",
        "Patspin India",
        "Marg Techno-Projects",
        "Challani Capital",
        "Concord Drugs",
        "Sri Ramakrishna Mills (Coimbatore)",
        "Yuranus Infrastructure",
        "Samyak International",
        "Max Heights Infrastructure",
        "Polymechplast Machines",
        "Rose Merc",
        "Amco India",
        "Williamson Magor & Co",
        "Shashijit Infraprojects",
        "Cityman",
        "Inland Printers",
        "Roselabs Finance",
        "Mediaone Global Entertainment",
        "National General Industries Limited",
        "Jagsonpal Finance & Leasing",
        "Hemang Resources",
        "Veejay Lakshmi Engineering Works",
        "Natural Biocon (India)",
        "Rajkamal Synthetics",
        "Transgene Biotek",
        "India Cements Capital",
        "Popular Estate Management",
        "Jupiter Infomedia",
        "Mangalam Timber Products",
        "Winsome Yarns",
        "Cyber Media India",
        "Global Capital Markets",
        "Mohit Industries",
        "Jindal Capital",
        "Raw Edge Industrial Solutions",
        "MSR India",
        "Venlon Enterprises",
        "Alfa Ica India",
        "Sonal Adhesives",
        "Bombay Wire Ropes",
        "Vinyoflex",
        "Libord Finance",
        "Response Informatics",
        "TCM",
        "Prakash Woollen & Synthetic Mills",
        "B2B Software Technologies",
        "Cybele Industries",
        "Indus Finance",
        "East India Drums And Barrels Manufacturing",
        "Arcotech",
        "National Steel & Agro Industries",
        "Triliance Polymers",
        "GACM Technologies Ltd. - (DVR)",
        "Omkar Pharmachem",
        "Intec Capital",
        "Maris Spinners",
        "Sahara Housingfina Corporation",
        "Ventura Textiles",
        "Swati Projects",
        "IEC Education",
        "Premier Capital Services",
        "Stanrose Mafatlal Investments & Finance",
        "Mandhana Retail Ventures",
        "Munoth Financial Services",
        "Gajanan Securities Services",
        "Richfield Financial Services",
        "Sudal Industries",
        "Zenith Fibres",
        "Easun Capital Markets",
        "IITL Projects",
        "Hindustan Agrigentics",
        "Poojawestern Metaliks",
        "Choksi Imaging",
        "Setubandhan Infrastructure",
        "Thomas Scott India",
        "Hindustan Fluoro Carbons",
        "Stephanotis Finance",
        "Veerhealth Care",
        "Neeraj Paper Marketing",
        "Asian Tea & Exports",
        "Zodiac-JRD-MKJ",
        "Pan Electronics India",
        "COSYN",
        "Veer Energy & Infrastructure",
        "Deco-mica",
        "Sarthak Industries",
        "JMD Ventures",
        "Sovereign Diamonds",
        "Family Care Hospitals",
        "Amin Tannery",
        "Laffans Petrochemicals",
        "Shree Pacetronix",
        "Sadhna Broadcast",
        "Nagreeka Capital & Infrastructure",
        "Rajath Finance",
        "TV Vision",
        "Infronics Systems",
        "Purshottam Investofin",
        "Annvrridhhi Ventures",
        "Ashiana Ispat",
        "Bangalore Fort Farms",
        "Adarsh Plant Protect",
        "Ironwood Education",
        "Zenith Healthcare",
        "Sylph Technologies",
        "Khoobsurat",
        "Danube Industries",
        "Sanblue Corporation",
        "AF Enterprises",
        "Utique Enterprises",
        "Sree Jayalakshmi Autospin",
        "Gold Line International Finvest",
        "Visagar Polytex",
        "SOFCOM Systems",
        "ACE men engg works",
        "Chennai Meenakshi Multispeciality Hospital",
        "Kavveri Telecom Products",
        "BC Power Controls",
        "Narendra Properties",
        "Greencrest Financial Services",
        "SP Capital Financing",
        "Prime Urban Development India",
        "Prima Industries",
        "Samsrita Labs",
        "Olympia Industries",
        "OCL Iron and Steel",
        "Sanghvi Forging & Engineering",
        "KSK Energy Ventures",
        "Kabra Drugs",
        "RKD Agri & Retail",
        "Jai Mata Glass",
        "ACI Infocom",
        "Shahi Shipping",
        "Citizen Infoline",
        "Madhusudan Industries",
        "Harish Textile Engineers",
        "Dynamic Industries",
        "TTI Enterprise",
        "Tejassvi Aaharam",
        "Sharma East India Hospitals & Medical Research",
        "Shrydus Industries",
        "LWS Knitwear",
        "IGC Industries",
        "Paos Industries",
        "Tavernier Resources",
        "HS India",
        "Abhishek Finlease",
        "Bacil Pharma",
        "Steel Strips Infrastructures",
        "GSB Finance",
        "Suncare Traders",
        "Kallam Textiles",
        "Ritesh International",
        "Tai Industries",
        "Miven Machine Tools",
        "Anka India",
        "ND Metal Industries",
        "MFL India",
        "Trans Freight Containers",
        "Subhash Silk Mills",
        "Howard Hotels",
        "Tirupati Tyres",
        "Virtual Global Education",
        "Shree Securities",
        "MRC Agrotech",
        "Shubham Polyspin",
        "California Software Company",
        "Mukand Engineers",
        "Polo Hotels",
        "Dynamic Archistructures",
        "Tradewell Holdings",
        "Thambbi Modern Spinning Mills",
        "Taparia Tools",
        "Genesis IBRC India",
        "CIL Securities",
        "Asia Pack",
        "Kaiser Corporation",
        "Indo Cotspin",
        "Jayshree Chemicals",
        "Adinath Exim Resources",
        "Sarup Industries",
        "Frontline Corporation",
        "KCL Infra Projects",
        "Rishabh Digha Steel & Allied Products",
        "Pentokey Organy (India)",
        "VR Films & Studios",
        "Jolly Merchants",
        "Ishita Drugs & Industries",
        "Inducto Steels",
        "Shree Bhavya Fabrics Ltd",
        "Anuroop Packaging",
        "Regent Enterprises",
        "Sterling Powergensys",
        "Neil Industries",
        "S & T Corporation",
        "Vijay Textiles",
        "Best Eastern Hotels",
        "Velan Hotels",
        "Mansi Finance (Chennai)",
        "Adhata Global Ltd.",
        "Nuway Organic Naturals India",
        "Unistar Multimedia",
        "Tokyo Finance",
        "RTCL",
        "Madhusudan Securities",
        "Integrated Proteins",
        "Valson Industries",
        "Asian Petro Products and Exports",
        "Alchemist Realty",
        "Viji Finance",
        "Paragon Finance",
        "SI Capital & Financial Services",
        "Panabyte Technologies",
        "Daulat Securities",
        "Zenlabs Ethica",
        "Shree Metalloys",
        "Modern Steel",
        "Colinz Laboratories",
        "SSPDL",
        "Reliable Ventures India",
        "Vishvprabha Ventures",
        "Octavius Plantations",
        "Bhakti Gems & Jewellery",
        "Mihika Industries",
        "Yash Innoventures",
        "Ras Resorts & Apart Hotels",
        "Croissance Ltd",
        "Caprolactam Chemicals",
        "DJS Stock & Shares",
        "Interactive Financial Services",
        "Kamanwala Housing Construction",
        "Square Four Projects India",
        "Quadrant Televentures",
        "Uniroyal Industries",
        "Fruition Venture",
        "Kotia Enterprises",
        "Cindrella Hotels",
        "Bloom Industries",
        "United Credit",
        "Gemstone Investments",
        "Adhbhut Infrastructure",
        "Jackson Investments",
        "SBEC Systems (India)",
        "Advance Lifestyles",
        "Sattva Sukun Lifecare",
        "Monotype India",
        "TechIndia Nirman",
        "Eastern Treads",
        "Gujarat Cotex",
        "Phaarmasia",
        "Mukat Pipes",
        "Deccan Bearings",
        "Norris Medicines",
        "Vamshi Rubber",
        "Paramount Cosmetics (India)",
        "Solid Containers",
        "CMI",
        "Rotographics India",
        "Tasty Dairy Specialities",
        "Ind Renewable Energy",
        "Interstate Oil Carrier",
        "Decillion Finance",
        "Rama Paper Mills",
        "Tuni Textile Mills",
        "Yash Management & Satellite",
        "Kunststofe Industries",
        "Karnavati Finance",
        "Classic Filaments",
        "Swarna Securities",
        "Samtex Fashions",
        "Prag Bosimi Synthetics",
        "BNR Udyog",
        "Ramsons Projects",
        "Triveni Glass",
        "Atlas Cycles (Haryana)",
        "Metalyst Forgings",
        "Lyons Corporate Market",
        "Gujarat Lease Financing",
        "KCD Industries India",
        "BKV Industries",
        "VK Global Industries",
        "SM Gold",
        "Gala Global Products",
        "Lypsa Gems & Jewellery",
        "Mudunuru",
        "Shree Karthik Papers",
        "NDA Securities",
        "Mehta Integrated Finance",
        "Yaan Enterprises",
        "Harmony Capital Services",
        "Inditrade Capital",
        "Sterling Greenwoods",
        "Raunaq lnternational",
        "Neelkanth",
        "Genomic Valley Biotech",
        "ECS Biztech",
        "Jaipan Industries",
        "Continental Chemicals",
        "Adcon Capital Services",
        "Cubical Financial Services",
        "RR Financial Consultants",
        "Ajel",
        "Sibar Auto Parts",
        "GCM Securities",
        "Duke Offshore",
        "Amalgamated Electricity Company",
        "Relic Technologies",
        "Maitri Enterprises",
        "Rap Corp",
        "Gayatri Highways",
        "Moongipa Capital Finance",
        "Solid Stone Co",
        "Rita Finance & Leasing",
        "Sharp Investments",
        "White Organic Agro",
        "Span Divergent",
        "Autolite (India)",
        "Syncom Healthcare",
        "Eurotex Industries & Exports",
        "Ecofinity Atomix",
        "TRC Financial Services",
        "Integrated Capital Services",
        "Ashtasidhhi Industries",
        "Disha Resources",
        "Sumeru Industries",
        "South Asian Enterprises",
        "York Exports",
        "Orosil Smiths India",
        "Konark Synthetic",
        "Mahaan Foods",
        "Shukra Bullions",
        "Asian Warehousing",
        "Garware Synthetics",
        "Bharat Bhushan Finance & Commodity Brokers",
        "Parmax Pharma",
        "VB Industries",
        "Chandni Machines",
        "Sri Nachammai Cotton Mills",
        "Yarn Syndicate",
        "Kiran Print Pack",
        "Helpage Finlease",
        "Interworld Digital",
        "Jiya Eco-Products",
        "Premier",
        "Tulip Star Hotels",
        "Usha Martin Education & Solutions",
        "Trustwave Securities",
        "Adinath Textiles",
        "Yunik Managing Advisors",
        "Shyamkamal Investments",
        "Ashish Polyplast",
        "Emmessar Biotech & Nutrition",
        "Kandagiri Spinning Millis",
        "Mid India Industries",
        "Arihant's Securities",
        "Natraj Proteins",
        "Sarvottam Finvest",
        "Elegant Floriculture & Agrotech (India)",
        "Market Creators",
        "Southern Latex",
        "Shivagrico Implements",
        "HB Leasing & Finance Company",
        "Crane Infrastructure",
        "Computer Point",
        "Goenka Business & Finance",
        "Perfect-Octave Media Projects",
        "Link Pharma Chem Limited",
        "Svam Software",
        "Switching Technologies Gunther",
        "JJ Finance Corporation",
        "Esaar (India)",
        "Deep Diamond India",
        "Shyam Telecom",
        "Gilada Finance & Investments",
        "Shree Rajiv Lochan Oil Extraction",
        "KGN Enterprises",
        "IMP Powers",
        "Shirpur Gold Refinery",
        "Trade-Wings",
        "Midas Infra Trade",
        "Radha Madhav Corporation",
        "Gradiente Infotainment",
        "Onelife Capital Advisors",
        "Avishkar Infra Realty",
        "India Lease Development",
        "VB Desai Financial Services",
        "Vivid Global Industries",
        "Garbi Finvest",
        "Spice Islands Industries",
        "Risa International",
        "NPR Finance",
        "KK Fincorp",
        "Northlink Fiscal & Capital Services",
        "Kashyap Tele-Medicines",
        "GKP Printing & Packaging",
        "Yogi Infra Projects",
        "Panth Infinity",
        "Phyto Chem India",
        "Rajdarshan Industries",
        "Jagjanani Textiles",
        "PBA Infrastructure",
        "Oswal Yarns",
        "Garware Marine Industries",
        "Ramchandra Leasing & Finance",
        "Gian Life Care",
        "Lippi Systems",
        "Mehta Securities",
        "Golechha Global Finance",
        "Norben Tea & Exports",
        "Groarc Industries India",
        "BFL Asset Finvest",
        "PS IT Infrastructure & Services",
        "BIL Energy Systems",
        "Parenteral Drugs (India)",
        "Castex Technologies",
        "STI India",
        "Vitesse Agro",
        "Velox Industries",
        "DCM Financial Services",
        "Radaan Media Works India",
        "RO Jewels",
        "UH Zaveri",
        "Southern Infosys",
        "Beryl Drugs",
        "Inani Securities",
        "Mitshi India",
        "Soni Medicare",
        "Organic Coatings",
        "Anjani Finance",
        "Vani Commercials",
        "Kush Industries",
        "Rander Corporation",
        "Triveni Enterprises",
        "Alexander Stamps & Coin",
        "Sharpline Broadcast",
        "Darshan Orna",
        "Ador Multi Products",
        "Kachchh Minerals",
        "Modern Shares & Stockbrokers",
        "Raj Packaging Industries",
        "Provestment Services",
        "Rajasthan Cylinders & Containers",
        "Polycon International",
        "Sri Lakshmi Saraswathi Textiles (Arni)",
        "Indo-City Infotech",
        "Bazel International",
        "Neueon Towers",
        "SV Trading & Agencies",
        "Pentamedia Graphics",
        "Sathavahana Ispat",
        "Surya India",
        "Golden Legand Leasing & Finance",
        "National Plywood Industries",
        "Satra Properties (India)",
        "Naksh Precious Metals",
        "Decipher Labs",
        "Eureka Industries",
        "KMF Builders & Developers",
        "Sparc Electrex",
        "Chemo Pharma Laboratories",
        "Vikalp Securities",
        "Tirth Plastic",
        "Rajputana Investment & Finance",
        "Seasons Textiles",
        "Prima Agro",
        "MPL Plastics",
        "Catvision",
        "Hathway Bhawani Cabletel & Datacom",
        "Nyssa Corporation",
        "Neo Infracon",
        "Amraworld Agrico",
        "Photoquip (India)",
        "Symbiox Investment & Trading Co",
        "Svaraj Trading & Agencies",
        "Lime Chemicals",
        "United Interactive",
        "Step Two Corporation",
        "Beryl Securities",
        "Jindal Leasefin",
        "FGP",
        "Vas Infrastructure",
        "Amforge Industries",
        "Yashraj Containeurs",
        "Mipco Seamless Rings Gujarat",
        "Econo Trade (India)",
        "Lords Ishwar Hotels",
        "Markobenz Ventures",
        "Mohota Industries",
        "Skyline Ventures India",
        "Pasupati Fincap",
        "Riga Sugar Co",
        "Tarai Foods",
        "Tarapur Transformers",
        "7NR Retail",
        "IMEC Services",
        "Pasari Spinning Mills",
        "Seven Hill Industries",
        "Galaxy Agrico Exports",
        "Bisil Plast",
        "Sanchay Finvest",
        "Shree Ganesh Elastoplast",
        "SC Agrotech",
        "Ladam Affordable Housing",
        "Padmanabh Alloys & Polymers",
        "Kakatiya Textiles",
        "Libord Securities",
        "Shree Steel Wire Ropes",
        "Santosh Fine Fab",
        "Cemantic Infra-Tech",
        "Millennium Online Solutions (India)",
        "Vaghani Techno Build",
        "ANS Industries",
        "Suryavanshi Spinning Mills",
        "Shree Hanuman Sugar & Industries",
        "Raasi Refractories",
        "Indergiri Finance",
        "Bhagawati Oxygen",
        "Olympic Oil Industries",
        "Unjha Formulations",
        "GTN Textiles",
        "Venmax Drugs & Pharmaceuticals",
        "Talwalkars Better Value Fitness",
        "Real Touch Finance",
        "Terrascope Ventures",
        "Steelco Gujarat",
        "Grand Foundry",
        "Dhanada Corporation",
        "Sankhya Infotech",
        "Net Pix Shorts Digital Media",
        "Tacent Projects",
        "Triton Corp",
        "Monind",
        "Chemiesynth (Vapi)",
        "Indo Euro Indchem",
        "Sea TV Network",
        "ISF",
        "RSC International",
        "Shakti Press",
        "Glittek Granites",
        "Vivanza Biosciences",
        "Euro-Leder Fashion",
        "Kkalpana Plastick",
        "Prism Medico & Pharmacy",
        "RLF",
        "Munoth Communication",
        "Pratiksha Chemicals",
        "Kuwer Industries",
        "Senthil Infotek",
        "Iykot Hitech Toolroom",
        "Gyan Developers & Builders",
        "Welterman International",
        "Vaxfab Enterprises",
        "Krishna Capital & Securities",
        "Rama Petrochemicals",
        "Sanathnagar Enterprises",
        "Octal Credit Capital",
        "RGF Capital Markets",
        "Sri Chakra Cement",
        "Trident Tools",
        "Pazel International",
        "Wellesley Corporation",
        "Times Green Energy (India)",
        "Amit International",
        "Ram Minerals & Chemicals",
        "Blue Coast Hotels",
        "Muzali Arts",
        "Mount Housing & Infrastructure",
        "Creative Eye",
        "Shree Salasar Investments",
        "Alps Industries",
        "Abate As Industries",
        "Integra Telecommunication & Software",
        "Nouveau Global Ventures",
        "Esha Media Research",
        "Dhanvantri Jeevan Rekha",
        "SRM Energy",
        "Ortin Global",
        "Ushakiran Finance",
        "BCL Enterprises",
        "OTCO International",
        "VCU Data Management",
        "Uniroyal Marine Exports",
        "Checkpoint Trends",
        "NMS Global",
        "Gallops Enterprise",
        "Trinity League India",
        "Aanchal Ispat",
        "Gagan Gases",
        "Alchemist Corporation",
        "Classic Leasing & Finance",
        "Shree Manufacturing Co",
        "UTL Industries",
        "Stanpacks India",
        "iStreet Network",
        "Agio Paper & Industries",
        "Darjeeling Ropeway Co",
        "Filmcity Media",
        "Aroma Enterprises (India)",
        "Texel Industries Ltd. - Partly Paidup (TEXELINPP)",
        "DQ Entertainment (International)",
        "Sirohia & Sons",
        "Viaan Industries",
        "Pact Industries",
        "Prime Capital Market",
        "B J Duplex Boards",
        "AMS Polymers",
        "Jain Marmo Industries",
        "Shashank Traders",
        "Ambassador Intra Holdings",
        "Minaxi Textiles",
        "Patidar Buildcon",
        "CJ Gelatine Products",
        "Enterprise International",
        "Nexus Surgical & Medicare",
        "Hasti Finance",
        "Mideast Portfolio Management",
        "Meyer Apparel",
        "Kumbhat Financial Services",
        "GK Consultants",
        "Sabrimala Industries India",
        "Supertex Industries",
        "Anna Infrastructures",
        "Longview Tea Co",
        "Objectone Information Systems",
        "Super Bakers",
        "Fraser & Company",
        "Lead Financial Services",
        "Devine Impex",
        "Ramgopal Polytex",
        "Polytex India",
        "Bloom Dekor",
        "Mystic Electronics",
        "Vinayak Polycon International",
        "Suncity Synthetics",
        "CDG Petchem",
        "Abhinav Leasing & Finance",
        "Ramasigns Industries",
        "Panafic Industrials",
        "Peeti Securities",
        "Hypersoft Technologies",
        "Rich Universe Network",
        "Golden Carpets",
        "Shamrock Industrial Company",
        "Mathew Easow Research Securities",
        "Saianand Commercial",
        "Manor Estates & Industries",
        "Nikki Global Finance",
        "Hindustan Bio Sciences",
        "Parker Agro Chem Exports",
        "Premier Synthetics",
        "Pankaj Polymers",
        "Devhari Exports (India)",
        "Navketan Merchants",
        "Technofab Engineering",
        "Nutraplus India",
        "Chromatic India",
        "Sri Amarnath Finance",
        "Shivamshree Businesses",
        "Kabra Commercial",
        "RCC Cements",
        "Univa Foods",
        "Pioneer Agro Extracts",
        "CHD Chemicals",
        "Shri Niwas Leasing & Finance",
        "Woodsvilla",
        "I Power Solutions India",
        "Kinetic Trust",
        "MPS Pharmaa",
        "Sturdy Industries",
        "Citi Port Financial Services",
        "Vision Cinemas",
        "Promact Impex",
        "Virgo Global",
        "TeleCanor Global",
        "Progrex Ventures",
        "Soma Papers & Industries",
        "Jayatma Industries",
        "First Fintec",
        "Mayur Floorings",
        "Haria Apparels",
        "Siddha Ventures",
        "Mukta Agriculture",
        "Agarwal Fortune India",
        "Integra Capital",
        "Sheshadri Industries",
        "Explicit Finance",
        "Hittco Tools",
        "Integrated Hitech",
        "Nutech Global",
        "International Data Management",
        "Hit Kit Global Solutions",
        "Universal Office Automation",
        "Longspur International Ventures",
        "Milestone Global",
        "Worldwide Aluminium",
        "Ambitious Plastomac Company",
        "AVI Products India",
        "Trio Mercantile & Trading",
        "Thirani Projects",
        "Quantum Digital Vision (India)",
        "BGIL Films & Technologies",
        "Shantai Industries",
        "Purohit Construction",
        "Flora Corporation",
        "Space Incubatrics Technologies",
        "Grandma Trading & Agencies",
        "Omega AG Seeds Punjab",
        "Zicom Electronic Security Systems",
        "Manraj Housing Finance",
        "BKM Industries",
        "Globe Commercials",
        "Talwalkars Healthclubs",
        "Cat Technologies",
        "AAR Commercial Co",
        "Indo-Global Enterprises",
        "TCI Finance",
        "MFS Intercorp",
        "Oswal Overseas",
        "Capricorn Systems Global Solutions",
        "Aravali Securities & Finance",
        "Brijlaxmi Leasing & Finance",
        "Sunraj Diamond Exports",
        "Maruti Securities",
        "Ganon Products",
        "Advance Syntex",
        "Bijoy Hans",
        "SGN Telecoms",
        "Vardhman Concrete",
        "Goyal Associates",
        "Raghunath International",
        "Jayabharat Credit",
        "KZ Leasing & Finance",
        "Scintilla Commercial & Credit",
        "Vision Corporation",
        "KLG Capital Services",
        "Sword-Edge Commercials",
        "Saffron Industries",
        "Sybly Industries",
        "Ace Engitech",
        "Ken Financial Services",
        "Brawn Biotech",
        "SHANTANU SHEOREY AQUAKULT LTD.",
        "Haria Exports",
        "Kuberan Global Edu Solutions",
        "Shree Precoated Steels",
        "Swagtam Trading & Services",
        "Futuristic Securities",
        "Khandelwal Extractions",
        "Krishna Filament Industries",
        "Prashant India",
        "Continental Controls",
        "Dharani Finance",
        "VXL Instruments",
        "Svarnim Trade Udyog",
        "Suryo Foods & Industries",
        "Tranway21 Technologies",
        "VKJ Infra Developers",
        "Mardia Samyoung Capillary Tubes Company",
        "Fenoplast",
        "Remi Elektrotechnik",
        "Regaliaa Realty",
        "Nishtha Finance and Investment (India)",
        "Typhoon Financial Services",
        "Pradip Overseas",
        "Real Strips",
        "Sujana Universal Industries",
        "Sri Krishna Constructions (India)",
        "Greenearth Resources & Projects",
        "Asia Capital",
        "RCI Industries & Technologies",
        "Neelkanth Rock-Minerals",
        "Corporate Merchant Bankers",
        "Ambition Mica",
        "M Lakhamsi Industries",
        "Sarthak Global",
        "Lexoraa Industries",
        "Jayatma Enterprises",
        "Williamson Financial Services",
        "Aadi Industries",
        "Sungold Capital",
        "Looks Health Services",
        "Tridev Infraestates",
        "Mega Nirman & Industries",
        "United Textiles",
        "PM Telelinks",
        "Wagend Infra Venture",
        "Gratex Industries",
        "Vintage Securities",
        "Ishaan Infrastructures & Shelters",
        "Galada Finance",
        "Konndor Industries",
        "Olympic Cards",
        "Aananda Lakshmi Spinning Mills",
        "Cindrella Financial Services",
        "PAE",
        "Aryan Share & Stock Brokers",
        "Voltaire Leasing & Finance",
        "Amerise Biosciences",
        "Delta Industrial Resources",
        "GSL Securities",
        "Epsom Properties",
        "Ashram Online Com",
        "Ontic Finserve",
        "Superior Finlease",
        "Golkonda Aluminium Extrusions",
        "Incon Engineers",
        "Union Quality Plastics",
        "Multipurpose Trading and Agencies",
        "Priya",
        "Clio Infotech",
        "Unitech International",
        "Omni AxS Software",
        "Siddheswari Garments",
        "Modella Woollens",
        "Beeyu Overseas",
        "Aditya Ispat",
        "Nihar Info Global",
        "Kuber Udyog",
        "Indra Industries",
        "Sparkling (India) Finshares",
        "Maximaa Systems",
        "Adharshila Capital",
        "Cox & Kings Financial Service",
        "Oceanaa Biotek Industries",
        "Alchemist",
        "Asya Infosoft",
        "Shivom Investment & Consultancy",
        "Trekkingtoescom",
        "Rainbow Denim",
        "SAB Events & Governance Now Media",
        "Infra Industries",
        "Edynamics Solutions",
        "Starlite Components",
        "Gujarat Metallic Coal & Coke",
        "Hi-Klass Trading & Investment",
        "Universal Arts",
        "Aviva Industries",
        "Sikozy Realtors",
        "Swadha Nature",
        "Oscar Global",
        "Kanel Industries",
        "Kanungo Financiers",
        "Amarnath Securities",
        "Shelter Infra Projects",
        "Natura Hue Chem",
        "Encode Packaging India",
        "Ekam Leasing & Finance Co",
        "Cistro Telelink",
        "Carnation Industries",
        "AVI Polymers",
        "Coral Newsprints",
        "Jainco Projects (India)",
        "Systematix Securities",
        "Taaza International",
        "Padmanabh Industries",
        "Decorous Investment & Trading Co",
        "Innocorp",
        "MP Agro Industries",
        "SW Investments",
        "Gravity (India)",
        "Elango Industries",
        "Atharv Enterprises",
        "Ashiana Agro Industries",
        "Omansh Enterprises",
        "Modex International Securities",
        "Action Financial Services (India)",
        "Auroma Coke",
        "Inceptum Enterprises",
        "Hind Securities and Credits Ltd",
        "Alka Securities",
        "Seasons Furnishings",
        "SBL Infratech",
        "Shree Rajeshwaranand Paper Mills",
        "Schablona India",
        "Euro Multivision",
        "GB Global",
        "Kwality Credit & Leasing",
        "Quest Financial Services",
        "Blueblood Ventures",
        "SIP Industries",
        "Remi Securities",
        "Bronze Infra-Tech",
        "Sun Source (India)",
        "Centerac Technologies",
        "Netripples Software",
        "Gajra Bevel Gears",
        "Adarsh Mercantile",
        "Shri Kalyan Holdings",
        "Mayur Leather Products",
        "Negotium International Trade",
        "KD Leisures",
        "Alps Motor Finance",
        "Mahaveer Infoway",
        "Richa Industries",
        "Padmalaya Telefilms",
        "Dhenu Buildcon Infra",
        "J R Foods",
        "Gujarat Winding Systems",
        "Thakkers Group",
        "Kome-on Communication",
        "Source Industries (India)",
        "Swadeshi Industries & Leasing",
        "Mahesh Developers",
        "Uniworth",
        "JPT Securities",
        "Tiaan Consumer",
        "Manglam Global Corporations",
        "Purple Entertainment",
        "Hemo Organic",
        "Shivansh Finserve",
        "Adjia Technologies",
        "Charms Industries",
        "Tricom Fruit Products",
        "Dolphin Medical Services",
        "Starlit Power Systems",
        "Saptak Chem & Business",
        "Diamant Infrastructure",
        "Omkar Overseas",
        "T Spiritual World",
        "Abhishek Infraventures",
        "Kiran Syntex",
        "Vallabh Steels",
        "Gopal Iron & Steels Company (Gujarat)",
        "Rajkot Investment Trust",
        "Pagaria Energy",
        "Premium Capital Market & Investment",
        "Spectra Industries",
        "B P Capital",
        "Triumph International Finance India",
        "Ledo Tea Company",
        "Divinus Fabrics",
        "Rekvina Laboratories",
        "Amit Securities",
        "Emmsons International",
        "Maxgrow India",
        "Aplaya Creations",
        "Universal Prime Aluminium",
        "Sashwat Technocrats",
        "GBL Industries",
        "Globus Corporation",
        "Mahavir Industries",
        "Genera Agri Corp",
        "India Infraspace",
        "Nicco Uco Alliance Credit",
        "ID Info Business Services",
        "SPV Global Trading",
        "GDL Leasing & Finance",
        "Blue Chip India",
        "Bhoruka Aluminium",
        "Mudra Financial Services",
        "Deccan Polypacks",
        "Brilliant Portfolios",
        "Melstar Information Technologies",
        "N2N Technologies",
        "Hindusthan Udyog",
        "Corporate Courier & Cargo",
        "SR Industries",
        "Gaekwar Mills",
        "AAR Shyam India Investment Company",
        "Magnus Retail",
        "Aneri Fincap",
        "Khyati Multimedia Entertainment",
        "Fourth Generation Information Systems",
        "Covidh Technologies",
        "Anand Projects",
        "Linaks Micro Electronics",
        "Surbhi Industries",
        "Goldcoin Health Foods",
        "Madhur Industries",
        "Geetanjali Credit & Capital",
        "TMT (India)",
        "Chambal Breweries & Distilleries",
        "Arcee Industries",
        "Rajeswari Infrastructure",
        "Regency Trust",
        "Jauss Polymers",
        "Concrete Credit",
        "Neogem India",
        "Sai Baba Investment and Commercial Enterprises",
        "Primuss Pipes & Tubes",
        "Ashari Agencies",
        "Ejecta Marketing",
        "Trans Asia Corporation",
        "Seshachal Technologies",
        "Jatalia Global Ventures",
        "Sanghi Corporate Services",
        "Raj Rayon Industries",
        "Vallabh Poly-Plast International",
        "Palsoft Infosystems",
        "Hind Commerce",
        "Dhruv Estates",
        "Rockon Enterprises Ltd",
        "Classic Global Finance & Capital",
        "Sagar Systech",
        "Shree Nidhi Trading Co",
        "Gagan Polycot India",
        "Five X Tradecom",
        "Aditri Gems & Jewels Industries",
        "Sarvamangal Marcantile Company",
        "Regal Entertainement and Consultants",
        "CES",
        "Meglon infra-Real (India)",
        "Galada Power & Telecommunication",
        "Revati Organics",
        "A & M Febcon",
        "Yash Trading & Finance",
        "Indo Credit Capital",
        "G-Tech Info-Training",
        "Baron Infotech",
        "Raymed Labs",
        "Rajvi Logitrade",
        "MPF Systems",
        "Mahan Industries",
        "Vega Jewellers",
        "Midland Polymers",
        "Cosboard Industries",
        "Remi Sales and Engineering",
        "Axon Ventures Ltd",
        "Solis Marketing",
        "Focus Industrial Resources",
        "Proaim Enterprises Ltd",
        "Coventry Coil-O-Matic (Haryana)",
        "Vishvas Projects",
        "Parab Infra",
        "Golden Tobacco",
        "Eastern Silk Industries",
        "Nanavati Ventures",
        "Silver Pearl Hospitality & Luxury Spaces",
        "Silicon Valley Infotech",
        "Funny Software",
        "Megh Mayur Infra",
        "Whitehall Commercial Company",
        "Indsoya",
        "Master Chemicals",
        "Ridhi Synthetics",
        "Antariksh Industries",
        "Varun Mercantile",
        "Sunrise Industrial Traders",
        "Mrugesh Trading",
        "Viksit Engineering",
        "Gold Rock Investments",
        "Shaw Construction",
        "Silveroak Commercials",
        "Unijolly Investments Company",
        "Hindustan Housing Company",
        "Magnanimous Trade & Finance",
        "Swastik Safe Deposit & Investments",
        "Procal Electronics India",
        "Sagar Soya Products",
        "Nibe Ordnance and Maritime",
        "India Radiators",
        "HEM Holdings & Trading"
    ]; // Add more stock names as needed

      for (const name of stockNames) {
        const url = `https://stock.indianapi.in/stock?name=${name}`; // Replace with actual API URL
        const options = {
          method: "GET",
          headers: {
            'X-Api-Key': "sk-live-8tS7HNRGHgefMfeQgdgftmw6FWitLp7rDCrDH8d3", // Replace with actual API key
          },
        };

        try {
          const response = await fetch(url, options);
          if (!response.ok) {
            throw new Error(`Failed to fetch data for ${name}`);
          }
          const data = await response.json();
          console.log(`Fetched data for ${name}:`, data);
          setStocks(prevStocks => [...prevStocks, ...(data.body || [])]);
        } catch (err) {
          setError(err.message);
        }
      }

      setLoading(false);
    };

    fetchStocks();
  }, []);

  return (
    <div className="p-5">
      <h1 className="text-xl font-bold">Pre-Market Stock Data</h1>

      {loading && <p>Loading...</p>}
      {error && <p className="text-red-500">Error: {error}</p>}

      {!loading && stocks.length === 0 && !error && <p>No stock data available.</p>}

      <ul>
        {stocks.map((stock, index) => (
          <li key={index} className="border p-2 my-2">
            <strong>{stock?.displayName || "N/A"}</strong>:{" "}
            {stock?.preMarketChange !== undefined
              ? `${stock.preMarketChange} (${stock.currency || "N/A"})`
              : "Data not available"}
          </li>
        ))}
      </ul>
    </div>
  );
}
